<div class="install">
  <h1><?php echo $this->__('Wootook! was successfully installed.')?></h1>
  <?php echo $this->getLayout()->getMessagesblock()->renderGroupedHtml()?>
  <p><?php echo $this->__('You have successfully installed Wootook!')?></p>
  <p><?php echo $this->__('You can now delete the <em>install/</em> folder to avoid security issues.')?></p>
  <p><button onclick="document.location.href='<?php echo $this->getUrl('/')?>'"><?php echo $this->__('Play!')?></button></p>
</div>